name: Build your apk

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: List APK directory
        run: ls /home/runner/work/ResponsiveLayout/ResponsiveLayout
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Lint
        run: npx eslint 

      - name: Make Gradlew Executable
        run: cd android && chmod +x ./gradlew

      - name: Build Android Debug APK
        run: cd android && ./gradlew assembleDebug
      

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
