name: Build your apk

on:
  push:
    branches: 
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Depedendencies
        run: npm install
        
      - name: Lint
        run : npx eslint 
        
      - name: open android 
        run: cd android
        
      - name: build release apk
        run : gradlew assembleRelease
